development:
  adapter: solr
  url: http://<%= ENV['SOLR_USER']%>:<%= ENV['SOLR_PASSWORD']%>@<%= ENV['SOLR_HOST']%>:<%= ENV['SOLR_PORT']%>/solr/<%= ENV['SOLR_PATH'] %>/
test: &test
  adapter: solr
  url: http://<%= ENV['SOLR_USER']%>:<%= ENV['SOLR_PASSWORD']%>@<%= ENV['SOLR_HOST']%>:<%= ENV['SOLR_PORT']%>/solr/<%= ENV['SOLR_PATH'] %>/
production:
  adapter: solr
  url: http://<%= ENV['SOLR_USER']%>:<%= ENV['SOLR_PASSWORD']%>@<%= ENV['SOLR_HOST']%>:<%= ENV['SOLR_PORT']%>/solr/<%= ENV['SOLR_PATH'] %>/


