default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: hydra_development
  
test:
  <<: *default
  database: hydra_test

production:
  <<: *default
  database: hydra_production
  username: hydra_user
  password: <%= ENV['DATABASE_PASSWORD'] %>
