# This is a sample config file that points to a solr server for each environment
development:
  url: http://<%= ENV['SOLR_USER']%>:<%= ENV['SOLR_PASSWORD']%>@<%= ENV['SOLR_HOST']%>:<%= ENV['SOLR_PORT']%>/solr/<%= ENV['SOLR_PATH'] %>/
test:
  url: http://<%= ENV['SOLR_USER']%>:<%= ENV['SOLR_PASSWORD']%>@<%= ENV['SOLR_HOST']%>:<%= ENV['SOLR_PORT']%>/solr/<%= ENV['SOLR_PATH'] %>/
production:
  url: http://<%= ENV['SOLR_USER']%>:<%= ENV['SOLR_PASSWORD']%>@<%= ENV['SOLR_HOST']%>:<%= ENV['SOLR_PORT']%>/solr/<%= ENV['SOLR_PATH'] %>/



