version: '3.4'	
# used for local testing	
# note only have either mfcs_export or mnt not both for conversions or hydra.	
services:	
  app:	
    build: 	
      context: ./	
      dockerfile: Dockerfile
    env_file:	
      - './env/.env.prod.hydra' 	
    volumes:	
      - ./hydra:/home/hydra	
      - ./solr:/home/hydra/solr      
      - ./scripts:/home/hydra/scripts	 	
      - ./mnt:/mnt  	
      - /home/hydra/tmp # don't mount tmp directory  	
    networks:	
      - hydra         	

  web:	
    extends: app	
    container_name: acda_portal	
    command: bash -c "bundle install; service cron start; gem install whenever; whenever --update-crontab; bundle exec rails s -p 3000 -b 0.0.0.0"	
    ports:	
      - "3000:3000"	
    depends_on:	
      - redis	
      - solr	
      - fcrepo	
      - db	
      - workers	

  workers:	
    extends: app	
    container_name: sidekiq	
    command: bundle exec sidekiq -C config/sidekiq.yml	
    depends_on:	
      - redis	
      - solr	
      - fcrepo	
      - memcached 	
      - db	
    stdin_open: true	
    tty: true             	

  memcached:	
    image: bitnami/memcached	
    container_name: memcached	
    ports:	
      - "11211"	
    networks:	
      - hydra	

  redis:	
    image: redis:alpine	
    container_name: redis	
    command: redis-server	
    ports:	
      - "6379"	
    volumes:	
      - redis:/var/lib/redis/data	
    restart: unless-stopped  	
    healthcheck:	
      test: redis-cli -h redis ping	
      interval: 30s	
      timeout: 3s	
      retries: 3                 	
    networks:	
      - hydra	

  fcrepo:	
    image: ghcr.io/samvera/fcrepo4:4.7.5	
    container_name: fcrepo	
    restart: on-failure    	
    volumes:	
      - fcrepo:/data:cached	
    ports:	
      - "8080:8080"  	
    networks:	
      - hydra      	

  solr:	
    image: solr:8.11.1	
    container_name: solr	
    restart: on-failure	
    ports:	
      - "127.0.0.1:8983:8983"	
    command:	
      - sh	
      - "-c"	
      - "solr-precreate hydra_dev /opt/solr/server/configsets/hydraconf"	
      - "&&"
      - "chown -R 8983:8983 /var/solr"
    volumes:	
      - ./solr/conf:/opt/solr/server/configsets/hydraconf        	
      - solr:/var/solr
    networks:	
      - hydra	   

  db:	
    container_name: db	
    image: postgres:14-alpine	
    ports:	
      - "5432"	
    env_file:	
      - './env/.env.prod.local.db'       	
    volumes:	
      - postgres:/var/lib/postgresql/data	
    restart: unless-stopped	
    healthcheck:	
        test: pg_isready -U postgres -h postgres	
        interval: 30s	
        timeout: 3s	
        retries: 3	
    networks:	
      - hydra	

  conversion:	
    build: 	
      context: ./conversion/	
      dockerfile: Dockerfile	
    container_name: acda_conversion	
    restart: always	
    environment:	
      - TERM=xterm	
    volumes:	
      - ./conversion/scripts:/convert/	
      - ./conversion/control:/control/	
      - ./mnt:/mnt	
    networks:	
      - hydra	

volumes:	
  postgres:	
  fcrepo:	
  redis:  	
  solr:	

networks:	
  hydra:	
    driver: bridge	
    driver_opts:	
      com.docker.network.bridge.name: br-hydra