terms:
  - id: Agriculture and Food
    term: Agriculture and Food
  - id: Animals
    term: Animals
  - id: Armed Forces and National Security
    term: Armed Forces and National Security
  - id: Arts, Culture, Religious
    term: Arts, Culture, Religious
  - id: Civil Rights and Liberties, Minority Issues
    term: Civil Rights and Liberties, Minority Issues
  - id: Commerce
    term: Commerce
  - id: Congress
    term: Congress
  - id: Constituent Relations
    term: Constituent Relations
  - id: Crime and Law Enforcement
    term: Crime and Law Enforcement
  - id: Economics and Public Finance
    term: Economics and Public Finance
  - id: Education
    term: Education
  - id: Emergency Management
    term: Emergency Management
  - id: Energy
    term: Energy
  - id: Environmental Protection
    term: Environmental Protection
  - id: Families
    term: Families
  - id: Finance and Financial Sector
    term: Finance and Financial Sector
  - id: Foreign Trade and International Finance
    term: Foreign Trade and International Finance
  - id: Government Operations and Politics
    term: Government Operations and Politics
  - id: Health
    term: Health
  - id: Housing and Community Development
    term: Housing and Community Development
  - id: Immigration
    term: Immigration
  - id: International Affairs
    term: International Affairs
  - id: Labor and Employment
    term: Labor and Employment
  - id: Law
    term: Law
  - id: Native Americans
    term: Native Americans
  - id: Public Lands and Natural Resources
    term: Public Lands and Natural Resources
  - id: Science, Technology, Communications
    term: Science, Technology, Communications
  - id: Social Sciences and History
    term: Social Sciences and History
  - id: Social Welfare
    term: Social Welfare
  - id: Sports and Recreation
    term: Sports and Recreation
  - id: Taxation
    term: Taxation
  - id: Transportation and Public Works
    term: Transportation and Public Works
  - id: Water Resources Development
    term: Water Resources Development
