terms:
  - id: Collection
    term: Collection
    active: true
  - id: Dataset
    term: Dataset
    active: true
  - id: Event
    term: Event
    active: true
  - id: Image
    term: Image
    active: true
  - id: InteractiveResource
    term: InteractiveResource
    active: true
  - id: MovingImage
    term: MovingImage
    active: true
  - id: PhysicalObject
    term: PhysicalObject
    active: true
  - id: Service
    term: Service
    active: true
  - id: Software
    term: Software
    active: true
  - id: Sound
    term: Sound
    active: true
  - id: StillImage
    term: StillImage
    active: true
  - id: Text
    term: Text
    active: true
