terms:
  - id: Collection
    term: Collection
    active: true
  - id: Dataset
    term: Dataset
    active: true
  - id: Event
    term: Event
    active: true
  - id: Image
    term: Image
    active: true
  - id: Interactive Resource
    term: Interactive Resource
    active: true
  - id: Moving Image
    term: Moving Image
    active: true
  - id: Physical Object
    term: Physical Object
    active: true
  - id: Service
    term: Service
    active: true
  - id: Software
    term: Software
    active: true
  - id: Sound
    term: Sound
    active: true
  - id: Still Image
    term: Still Image
    active: true
  - id: Text
    term: Text
    active: true
